version: '3.9'

services:

  postgres:
      container_name: 'postgres-cdc'
      hostname: postgres
      image: postgres:alpine
      ports: 
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-cdc'
    ports:
      - 5672:5672
      - 15672:15672

